import { Sidebar } from "@/components/Common/AntdItem/Sidebar/Sidebar";
import ContentNavWrapper from "@/components/Common/ContentNavWrapper/ContentNavWrapper";
import { theme } from "@/theme/themeConfig";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, Layout } from "antd";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { Toaster } from "sonner";

const Optima = localFont({
  src: [
    { path: '../../public/fonts/Optima/Optima-regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/Optima/Optima-regular_italic.ttf', weight: '400', style: 'italic' },
    { path: '../../public/fonts/Optima/Optima-medium.ttf', weight: '500', style: 'normal' },
    { path: '../../public/fonts/Optima/Optima-bold.ttf', weight: '700', style: 'normal' },
  ],
});

const Philosopher = localFont({
  src: [
    {
      path: '../../public/fonts/Philosopher/Philosopher-regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Philosopher/Philosopher-regular_Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    { path: '../../public/fonts/Philosopher/Philosopher-bold.ttf', weight: '500', style: 'normal' },
    {
      path: '../../public/fonts/Philosopher/Philosopher-bold_Italic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
});
export const metadata: Metadata = {
  title: "B2B Panel",
  description: "Generated by create next app",
};
// const {  Content } = Layout;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Optima.className} ${Philosopher.className}`}
      >
        <AntdRegistry>
          <ConfigProvider theme={theme}>
            <Layout>
              <Sidebar />
              <Toaster />
              {/* <Layout className="ml-[280px]" >
                <NavBar />
                <AppContent>{children}</AppContent>
              </Layout> */}
              <ContentNavWrapper>
                {
                  children
                }
              </ContentNavWrapper>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
